import { useEffect, useState } from 'react';
interface Health { ok:boolean; comfy:boolean; anima:{configured:boolean;error?:string} }
export function AnimaPanel() {
  const [health,setHealth]=useState<Health|undefined>(); const [prompt,setPrompt]=useState('top-down anime game character, full body, readable silhouette, neutral pose, clean isolated background');
  const [negative,setNegative]=useState('text, watermark, multiple characters, cropped feet, malformed hands'); const [reference,setReference]=useState(''); const [strength,setStrength]=useState(.75); const [status,setStatus]=useState('Not queued');
  const refresh=async()=>{try{setHealth(await (await fetch('http://127.0.0.1:4817/health')).json())}catch{setHealth(undefined)}}; useEffect(()=>{void refresh()},[]);
  const queue=async()=>{setStatus('Queueing…');try{const response=await fetch('http://127.0.0.1:4817/anima/queue',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt,negativePrompt:negative,width:1024,height:1024,steps:8,referenceImage:reference||undefined,ipAdapterStrength:reference?strength:undefined})});const result=await response.json();if(!response.ok)throw new Error(result.error??'Generation failed');setStatus(`Queued ${result.prompt_id} · seed ${result.seed}`)}catch(error){setStatus(error instanceof Error?error.message:String(error))}};
  return <section className="anima-panel"><div className="panel-title-row"><strong>Anima Turbo</strong><button className="mini" onClick={()=>void refresh()}>Reconnect</button></div><div className={`connection ${health?.comfy&&health.anima.configured?'ready':'offline'}`}>{health?.comfy&&health.anima.configured?'ComfyUI and workflow ready':health?.anima.error??'Bridge offline — run npm run dev'}</div><label>Prompt<textarea rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>Negative<textarea rows={2} value={negative} onChange={e=>setNegative(e.target.value)}/></label><label>Reference image<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Optional ComfyUI input filename"/></label><label>IP-Adapter strength <span>{strength.toFixed(2)}</span><input type="range" min="0" max="1.5" step="0.05" value={strength} onChange={e=>setStrength(Number(e.target.value))}/></label><button className="primary" disabled={!health?.comfy||!health.anima.configured} onClick={()=>void queue()}>Generate candidate</button><small>{status}</small></section>;
}
