import { useCallback, useEffect, useMemo, useState } from 'react';
import { demoProject, demoScene } from '../core/demo';
import type { SceneDocument, SceneObjectDocument } from '../core/types';
import { AnimaPanel } from './AnimaPanel';
import { PreviewCanvas } from './PreviewCanvas';
import { useHistory } from './useHistory';

const storageKey='pixelator.scene.v1';
function loadScene():SceneDocument{try{const saved=localStorage.getItem(storageKey);return saved?JSON.parse(saved):structuredClone(demoScene)}catch{return structuredClone(demoScene)}}
function Field({label,value,onChange,type='text'}:{label:string;value:string|number;onChange:(value:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}

export function App(){
  const history=useHistory(loadScene()); const scene=history.value;
  const [selectedId,setSelectedId]=useState<string|undefined>(scene.objects[0]?.id); const [playing,setPlaying]=useState(false); const [debugGrid,setDebugGrid]=useState(true); const [bottomTab,setBottomTab]=useState<'anima'|'json'|'plan'>('anima'); const [metrics,setMetrics]=useState('Starting preview…');
  const [scenePath,setScenePath]=useState('scenes/village.scene.json'); const [serverRevision,setServerRevision]=useState<number|undefined>(); const [fileStatus,setFileStatus]=useState('Browser draft');
  const [request,setRequest]=useState('Add a ruined shrine, two patrolling enemies, and a clear win condition. Preserve the warm lantern palette.'); const [plan,setPlan]=useState<string[]>([]);
  useEffect(()=>localStorage.setItem(storageKey,JSON.stringify(scene)),[scene]);
  useEffect(()=>{void fetch('http://127.0.0.1:4817/project').then(async response=>{if(!response.ok)throw new Error('Project bridge unavailable');return response.json()}).then((payload:{scenePath:string;scene:SceneDocument})=>{history.reset(payload.scene);setScenePath(payload.scenePath);setServerRevision(payload.scene.revision);setSelectedId(payload.scene.objects[0]?.id);setFileStatus('Loaded from project files')}).catch(()=>setFileStatus('Bridge offline — editing browser draft'))},[]);
  const selected=useMemo(()=>scene.objects.find(object=>object.id===selectedId),[scene,selectedId]);
  const updateObject=useCallback((id:string,updater:(object:SceneObjectDocument)=>SceneObjectDocument)=>history.set(current=>({...current,revision:current.revision+1,objects:current.objects.map(object=>object.id===id?updater(object):object)})),[history.set]);
  const moveObject=useCallback((id:string,x:number,y:number)=>updateObject(id,object=>({...object,position:{x,y}})),[updateObject]);
  const addObject=()=>{const id=`prop_${Date.now()}`;const object:SceneObjectDocument={id,name:'New Prop',kind:'prop',position:{x:640,y:448},size:{x:64,y:64},rotation:0,color:'#c0a36e',layer:2,tags:[],components:[]};history.set(current=>({...current,revision:current.revision+1,objects:[...current.objects,object]}));setSelectedId(id)};
  const removeObject=()=>{if(!selectedId)return;history.set(current=>({...current,revision:current.revision+1,objects:current.objects.filter(object=>object.id!==selectedId)}));setSelectedId(undefined)};
  const saveProject=async()=>{if(serverRevision===undefined){setFileStatus('Cannot save until bridge is connected');return}setFileStatus('Saving…');try{const response=await fetch('http://127.0.0.1:4817/project/scene',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:scenePath,expectedRevision:serverRevision,scene})});const result=await response.json();if(!response.ok)throw new Error(result.error??'Save failed');history.reset(result.scene);setServerRevision(result.scene.revision);setFileStatus(`Saved · checkpoint ${result.checkpoint}`)}catch(error){setFileStatus(error instanceof Error?error.message:String(error))}};
  const exportProject=async()=>{setFileStatus('Exporting…');try{const response=await fetch('http://127.0.0.1:4817/project/export',{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error??'Export failed');setFileStatus(`Web export: ${result.output}`)}catch(error){setFileStatus(error instanceof Error?error.message:String(error))}};
  const createPlan=()=>{setPlan([`Brief: ${request}`,'1. Preserve the current movement loop and stable IDs.','2. Add scene objects and mechanics as revision-guarded patches.','3. Test the objective, enemy pressure, camera, and reset path.','4. Queue only required Anima Turbo assets using one visual profile.','5. Approve chosen candidates, then replace placeholders without changing gameplay IDs.']);setBottomTab('plan')};
  return <main className="studio-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">PX</span><div><strong>Pixelator</strong><small>{demoProject.name} · r{scene.revision} · {fileStatus}</small></div></div><div className="command"><input value={request} onChange={e=>setRequest(e.target.value)}/><button onClick={createPlan}>Plan with Codex</button></div><div className="toolbar"><button disabled={!history.canUndo} onClick={history.undo}>Undo</button><button disabled={!history.canRedo} onClick={history.redo}>Redo</button><button className={playing?'active':''} onClick={()=>setPlaying(value=>!value)}>{playing?'Stop':'Play'}</button><button onClick={()=>void saveProject()}>Save</button><button onClick={()=>void exportProject()}>Export</button></div></header>
    <aside className="left-panel"><div className="panel-heading"><span>Scene</span><button className="mini" onClick={addObject}>+ Object</button></div><div className="scene-name">◇ {scene.name}</div><div className="object-list">{scene.objects.map(object=><button key={object.id} className={selectedId===object.id?'selected':''} onClick={()=>setSelectedId(object.id)}><span className={`kind kind-${object.kind}`}/><span><strong>{object.name}</strong><small>{object.kind} · {object.id}</small></span></button>)}</div><div className="library"><div className="panel-heading">Behavior library</div>{['top-down-movement','health','patrol','chase','interactable','win-zone'].map(behavior=><span key={behavior}>{behavior}</span>)}</div></aside>
    <section className="workspace"><div className="preview-toolbar"><span className={`status-dot ${playing?'live':''}`}/><strong>{playing?'Playable preview':'Scene editor'}</strong><small>{metrics}</small><label className="check"><input type="checkbox" checked={debugGrid} onChange={e=>setDebugGrid(e.target.checked)}/> Grid</label><span className="hint">{playing?'Move with WASD or arrows':'Drag objects; positions snap to grid'}</span></div><PreviewCanvas scene={scene} selectedId={selectedId} playing={playing} debugGrid={debugGrid} onSelect={setSelectedId} onMove={moveObject} onMetrics={setMetrics}/></section>
    <aside className="right-panel"><div className="panel-heading">Inspector</div>{selected?<><div className="inspector-id">{selected.id}</div><Field label="Name" value={selected.name} onChange={value=>updateObject(selected.id,object=>({...object,name:value}))}/><label>Kind<select value={selected.kind} onChange={e=>updateObject(selected.id,object=>({...object,kind:e.target.value as SceneObjectDocument['kind']}))}>{['player','npc','enemy','prop','trigger'].map(kind=><option key={kind}>{kind}</option>)}</select></label><div className="field-row"><Field label="X" type="number" value={selected.position.x} onChange={value=>moveObject(selected.id,Number(value),selected.position.y)}/><Field label="Y" type="number" value={selected.position.y} onChange={value=>moveObject(selected.id,selected.position.x,Number(value))}/></div><div className="field-row"><Field label="Width" type="number" value={selected.size.x} onChange={value=>updateObject(selected.id,object=>({...object,size:{...object.size,x:Number(value)}}))}/><Field label="Height" type="number" value={selected.size.y} onChange={value=>updateObject(selected.id,object=>({...object,size:{...object.size,y:Number(value)}}))}/></div><Field label="Layer" type="number" value={selected.layer} onChange={value=>updateObject(selected.id,object=>({...object,layer:Number(value)}))}/><Field label="Color" type="color" value={selected.color} onChange={value=>updateObject(selected.id,object=>({...object,color:value}))}/><div className="component-list"><strong>Components</strong>{selected.components.map((component,index)=><span key={`${component.type}-${index}`}>{component.type}</span>)}</div><button className="danger" onClick={removeObject}>Remove object</button></>:<p>Select an object.</p>}</aside>
    <section className="bottom-panel"><nav><button className={bottomTab==='anima'?'active':''} onClick={()=>setBottomTab('anima')}>Anima queue</button><button className={bottomTab==='plan'?'active':''} onClick={()=>setBottomTab('plan')}>Codex plan</button><button className={bottomTab==='json'?'active':''} onClick={()=>setBottomTab('json')}>Project JSON</button></nav><div className="bottom-content">{bottomTab==='anima'&&<AnimaPanel/>}{bottomTab==='plan'&&<pre>{plan.length?plan.join('\n\n'):'Describe a change above, then create a reviewable plan.'}</pre>}{bottomTab==='json'&&<pre>{JSON.stringify(scene,null,2)}</pre>}</div></section>
  </main>;
}
